variables:
    EOS_PATH: "/eos/home-s/spigazzi/www/docs/h4analysis/"
    EOS_MGM_URL : "root://eoshome-s.cern.ch"
    CI_OUTPUT_DIR: "public"

stages:
    - docs
    - deploy 

# Compile the docs
compilation:
    stage: docs
    image: gitlab-registry.cern.ch/ci-tools/ci-worker:cc7
    script:
    - yum -y install python3 pip3 locmap
    - pip3 install sphinx breathe sphinx_rtd_theme 
    - make docs
    - mkdir "$CI_OUTPUT_DIR"
    - mv docs/build/html/* "$CI_OUTPUT_DIR"
    artifacts:
        paths:
        # Upload as an artifact the folder where the output has been generated
        # This will attach to the job the output. It can be browsed or downloaded
        - "$CI_OUTPUT_DIR"
    
# Deploy to an EOS folder the contents generated
deployment:
    stage: deploy
      # Only when the master branch is pushed
    only:
        - master
    # Custom docker image providing the needed tools to deploy in EOS
    image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer:latest
    script:
        - deploy-eos

